Create Broken.java
This was compiled with run-broken.bat. This is the full file. This file produces this error:
Error: Could not find or load main class Broken.class
Caused by: java.lang.ClassNotFoundException: Broken.class